### ISSUE TITLE
[OOB 5.6] NUCLEO_F401RE/411RE have a pin conflict at D13 between LED and SPI_SCK working with Atmel RF233 shield  

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-mesh-minimal#126]
NUCLEO_F401RE/411RE failed to read/write SPI registers to Atmel RF233 shield when LED is using. because SPI1_SCK and LED are using the same pin D13, which is required by the 6LowPAN RF233 shield. for using the shield, LED should be disabled customizing mbed_app.json as following.

"NUCLEO_F401RE": {
            "LED": "NC",

"NUCLEO_F411RE": {
            "LED": "NC",

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3200

**Comment by SeppoTakalo** [comment]
Thanks for the info.
I will add this into our `mbed_app.json`

**Comment by soramame21** [comment]
@SeppoTakalo Thanks for the quick fix.
