### ISSUE TITLE
K22F Connecting... never returns

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-mesh-minimal#15]
K22F + Atmel Shield
mbed-os-5.1.0-rc5
same result with GCC_ARM, ARM, IAR toolchains

mbed-os-example-mesh-minimal (a2beca3d397a)
|- atmel-rf-driver (a16a4ed6f6e8)
`- mbed-os (dd36dc4228b5)

```
Connecting...
|
```

**Comment by hasnainvirk** [comment]
@maclobdell I think this is not application issue. So you should close the issue.

**Comment by maclobdell** [comment]
documented on the board platform page https://developer.mbed.org/forum/platform-72-FRDM-K22F-community/topic/26490/
