### ISSUE TITLE
App config settings non linear/misplaced

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-mesh-minimal#153]
Told [how to modify radio type](https://github.com/ARMmbed/mbed-os-example-mesh-minimal#changing-the-radio-driver-optional) after instructions to compile. Compile instructions reference `configs/mesh_6lowpan.json` but told here to modify `mbed_app.json`. 

At the time of first compile, I would have compiled for the wrong type of radio and flashed the program before reading instructions for changing radio type.

These instructions should be written or linked before the first compile.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3329

**Comment by MarceloSalazar** [comment]
@SeppoTakalo

**Comment by SeppoTakalo** [comment]
Fixed in #162
