### ISSUE TITLE
NUCLEO F401RE + MCR20 Only works with LED set to NC

### ISSUE THREAD

**Issue by sarahmarshy** [ARMmbed/mbed-os-example-mesh-minimal#154]
Basically what the title says. The board will only connect to the network when using `mbed_app.json` and not the suggesed `mesh_6lowpan.json`. The only difference for 6LowPan seems to be that `mbed_app.json` [sets the LED to NC](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/blob/master/mbed_app.json#L40).

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3332

**Comment by MarceloSalazar** [comment]
@SeppoTakalo have you share your thoughts?

**Comment by terhei** [comment]
LED pin is overlapping with radioshield SPI pins. 
PR to fix this: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/159

**Comment by SeppoTakalo** [comment]
Fixed in #160
