### ISSUE TITLE
Support nRF52840

### ISSUE THREAD

**Issue by Cheong2K** [ARMmbed/mbed-os-example-mesh-minimal#171]
When will this example support the nRF52840 SoC that has internal 802.15.4 capability?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3437

**Comment by TuomoHautamaki** [comment]
This one is similar to https://github.com/ARMmbed/nanostack-border-router/issues/86

So, not an application issue but would require RF driver from Nordic.
No work to be done for the application. Thus, closing
