### ISSUE TITLE
Error when using KW24D (IAR) with optimized Thread configuration

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-os-example-mesh-minimal#176]
Compiled KW24D with IAR8 compiler using optimized `mesh_thread.json`.
 * "value": "KW24D"
 * "enable-led-control-example": false,
 * "macros": ["MBEDTLS_USER_CONFIG_FILE=\"mbedtls_config.h\""],
 * "nanostack-hal.event_loop_thread_stack_size": 2048,
 * "mbed-mesh-api.heap-size": 15000,

Application produces following output:
```
Connecting...
Mutex 1fffa9cc error -6: Not allowed in ISR context
```

The application is working fine when compiled with GCC_ARM or ARM compilers.

NOTE! "mbed-mesh-api.use-malloc-for-heap": was not set

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3539

**Comment by SeppoTakalo** [comment]
I'm closing this for two reasons:
* IAR8 is not yet supported toolchain
* MCR20A radio driver is already tested in CI and this failure is not visible: https://jenkins-internal.mbed.com/job/ARMmbed/job/mbed-os-example-mesh-minimal/job/PR-186/2/artifact/log_8034_thread_mesh_minimal_smoke_k64f_mcr20/
