### ISSUE TITLE
Error with U-Blox EVK and 6LoWPAN shield

### ISSUE THREAD

**Issue by gggekov** [ARMmbed/mbed-os-example-mesh-minimal#179]
I try to connect a U-Blox EVK board with a 6LoWPAN Atmel shield to a router.  I am using GCC_ARM compiler. 
On the EVK board I am getting the following output: 
`
Connecting...
Start mesh-minimal application
Build: Mar 16 2018 16:59:06
Mesh type: 3
pins not configured. Skipping the LED control.
`
Do you have any suggestion how this can be resolved? 

Thank you! 
PS: Next week I will be on a business trip, Ashok will follow up on this issue.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3555

**Comment by SeppoTakalo** [comment]
This is not actually and error. LED pins are not defined for this board, so the LED control example does not start. But it still joins the network.

Documentation mentions the LEDS in the [Requirements for the hardware](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/blob/master/README.md#requirements-for-hardware) section.
`You also need to check how LEDs and buttons are configured for your hardware, and update .json accordingly.`

Boards that already have pins defined are K64F, K66F, NCS36510, KW24D.
