### ISSUE TITLE
[mbed-os-5.9.0-oob] User button doesn't work on NUCLEO_F429ZI

### ISSUE THREAD

**Issue by soramame21** [ARMmbed/mbed-os-example-mesh-minimal#193]
### Description

User Button doesn't work with LED control on NUCLEO_F429ZI. 

### Customization
Added following lines into configs\mesh_6lowpan.json
```
        "NUCLEO_F429ZI":  {
            "LED": "LED_RED",
            "BUTTON": "USER_BUTTON"
        } 
```       
### Type
[ ] Question  
[ ] Enhancement  
[X] Bug  
### Tag
mbed-os-5.9.0-rc2
### Toolchain
GCC_ARM | ARM
### Build commands
mbed compile -m NUCLEO_F429ZI -t ARM --app-config configs\mesh_6lowpan.json
mbed compile -m NUCLEO_F429ZI -t GCC_ARM --app-config configs\mesh_6lowpan.json
### How to fix
Once following line was commented or deleted, the Blue User button started working.
line 201 in mesh_led_control_example.cpp
`my_button.mode(PullUp);`

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3707

**Comment by jarlamsa** [comment]
Fixed in https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/197
