### ISSUE TITLE
EUI64 is not constant when using MCR20 radio

### ISSUE THREAD

**Issue by artokin** [ARMmbed/mbed-os-example-mesh-minimal#202]
This issue is generated from https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/199.

When using Thread configuration and MCR20 radio the method "device_eui64_get" returns slightly different EUI64 every time when the device is restarted. The actual result is visible here: https://github.com/ARMmbed/mbed-os-example-mesh-minimal/issues/199#issuecomment-402891001

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3748

**Comment by artokin** [comment]
This issue is copied to MCR20 driver repository: https://github.com/ARMmbed/mcr20a-rf-driver/issues/17

**Comment by artokin** [comment]
Closed as https://github.com/ARMmbed/mcr20a-rf-driver/issues/17 is now fixed.
