### ISSUE TITLE
Invalid EUI64 address for atmel radio

### ISSUE THREAD

**Issue by jarlamsa** [ARMmbed/mbed-os-example-mesh-minimal#219]
mbed-os version: mbed-os-5.10.0-rc2
mesh-minimal version: mbed-os-5.10.0-oob

Toolchain: GCC

Output:
Start mesh-minimal application
Build: Sep 14 2018 13:46:16
Mesh type: MBED_CONF_NSAPI_DEFAULT_MESH_TYPE
Mbed OS version: 5.10.0
Device EUI64 address = 00:00:00:00:00:00:00:00
Connecting...

Expected output:
Device EUI64 address should be something else than 0

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3884

**Comment by KariHaapalehto** [comment]
Issue corrected with: https://github.com/ARMmbed/mbed-os/pull/8975
