### ISSUE TITLE
Cannot build for ARMCC on boards without TRNG

### ISSUE THREAD

**Issue by c1728p9** [ARMmbed/mbed-os-example-mesh-minimal#24]
Since there is no entropy source some TLS functions are not present. These functions are never used directly, so GCC ignores them. ARMCC does not, and instead shows linker errors. Either directions to enable software only entropy need to be added, or the functions using the unavailable TLS functions need to be switched out.

CC: @SeppoTakalo @sg-

**Comment by SeppoTakalo** [comment]
Please open this bug on mbed OS repo.
If mbed OS cannot build on platforms without TRNG, then it is a mbed OS issue.

**Comment by c1728p9** [comment]
This should be fixed by https://github.com/ARMmbed/mbed-os/pull/2915.
