### ISSUE TITLE
5.13 OOB - Quotation missing from README.md "nsapi.default-mesh-type" example entries.

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-mesh-minimal#260]
![image](https://user-images.githubusercontent.com/13328062/59029050-e82f5000-8865-11e9-880c-c18e06720496.png)

**Comment by korjaa** [comment]
-> cannot be copy-pasted.

**Comment by korjaa** [comment]
https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/261

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4353
