### ISSUE TITLE
5.13 OOB - UX - README.md references ".json", is it "mbed_app.json"?

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-mesh-minimal#263]

**Comment by adbridge** [comment]
5.13 OOB UX ?? What do you mean?

**Comment by korjaa** [comment]
User eXperience

**Comment by korjaa** [comment]
This is minor visual thing, but I think it would make more sense if it read `mbed_app.json`.

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4360

**Comment by michalpasztamobica** [comment]
Fixed with https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/269
