### ISSUE TITLE
5.13 OOB - Atmel AT86RF233 firefly link is broken.

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-mesh-minimal#264]
https://firefly-iot.com/product/firefly-arduino-shield-2-4ghz/ results in "Unable to connect"

**Comment by SeppoTakalo** [comment]
Seems that L-Tek has changed their URLs.

This one is working:
https://l-tek.si/web-shop/l-tek-6lowpan-arduino-shield-2-4ghz/

@artokin will you update?

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4359

**Comment by michalpasztamobica** [comment]
l-tek's 6lowpan arduino shield mentioned above uses AT86RF212, not AT86RF233. 
AT86RF212 is a sub-GHz band device, while AT86RF233 is 2.4 GHz.

**Comment by michalpasztamobica** [comment]
Confirmed with @kimlep01 from Infrastructure team, that this is the right link, indeed.

**Comment by michalpasztamobica** [comment]
The confusion has been clarified with the web shop, they updated the schematic and now it clearly shows that AT86RF233 has been used.

**Comment by michalpasztamobica** [comment]
Fixed with https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/269

**Comment by nbrunner** [comment]
The link https://www.l-tek.com/web-shop/l-tek-6lowpan-arduino-shield-2-4ghz/ return to a "Oops! That page can’t be found."
