### ISSUE TITLE
5.13 OOB - WiSUN requires jumper wire to work which is not obivious from README.md.

### ISSUE THREAD

**Issue by korjaa** [ARMmbed/mbed-os-example-mesh-minimal#267]
![image](https://user-images.githubusercontent.com/13328062/59102607-3bbc9f00-8935-11e9-9a46-3d7dc00270f2.png)

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-4356

**Comment by michalpasztamobica** [comment]
Fixed with https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/269
