### ISSUE TITLE
compilation error with GCC_ARM

### ISSUE THREAD

**Issue by balamk07** [ARMmbed/mbed-os-example-mesh-minimal#27]
The example generates following compilation error with GCC_ARM.

$ mbed compile -m K64F -t GCC_ARM
Building project mbed-os-example-mesh-minimal (K64F, GCC_ARM)
Scan: .
Scan: FEATURE_BLE
Scan: FEATURE_CLIENT
Scan: FEATURE_COMMON_PAL
Scan: FEATURE_UVISOR
Scan: FEATURE_IPV4
Scan: FEATURE_IPV6
Scan: FEATURE_STORAGE
Scan: mbed
Scan: env
[ERROR] Feature 'NANOSTACK' is not a supported features
[mbed] ERROR: "python" returned error code 1.

The export command for external toolchain (uVision5) also fails with the same error.

**Comment by SeppoTakalo** [comment]
Issue is now fixed with mbed OS 5.2 release.
