### ISSUE TITLE
Update LED and BUTTON pin names according to standard

### ISSUE THREAD

**Issue by jeromecoutant** [ARMmbed/mbed-os-example-mesh-minimal#330]
### Description of defect

Please update mbed_app.json according to latest pin standard.

- Avoid LED_RED => use LED1
- Use BUTTON1

@MarceloSalazar @gpsimenos 

Thx

#### Target(s) affected by this defect ?

ALL

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os master

**Comment by ciarmcom** [comment]
@jeromecoutant thank you for raising this issue.Please take a look at the following comments:

Could you add some more detail to the description? A good description should be at least 25 words.
What toolchain(s) are you using?
It would help if you could also specify the versions of any tools you are using?
 How can we reproduce your issue?

NOTE: If there are fields which are not applicable then please just add 'n/a' or 'None'. This indicates to us that at least all the fields have been considered.
Please update the issue header with the missing information, the issue will not be mirrored to our internal defect tracking system or investigated until this has been fully resolved.

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by MarceloSalazar** [comment]
Thanks @jeromecoutant , we'll look into this in the upcoming days

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by gpsimenos** [comment]
Addressed in #334

**Comment by ciarmcom** [comment]
@jeromecoutant it has been 5 days since the last reminder. Could you please update the issue header as previously requested?

**Comment by jeromecoutant** [comment]
> Addressed in #334

Github tip :-)
In #334 description, you should have added line "fix #330",
so Github could close automatically linked issue when merging :-)
