### ISSUE TITLE
CMake build fails due to `Unknown CMake command "mbed_set_mbed_target_linker_script"`

### ISSUE THREAD

**Issue by Patater** [ARMmbed/mbed-os-example-mesh-minimal#331]
### Description of defect

Error Message

Failed when executing: python -u ../mbed-os/tools/test/examples/examples.py  compile GCC_ARM --mcu NUCLEO_F767ZI --cmake -v   Reason: hudson.AbortException: script returned exit code 1

Standard Output

Last 100 lines from the log:
Total Flash memory (text + data): 33624(+33624) bytes

#### End of STDOUT/STDERR ####

[EXAMPLES]> WARNING  Test for mbed-os-example-blinky will not be generated.
[EXAMPLES]> INFO     In folder 'mbed-os-example-blinky-baremetal'
[EXAMPLES]> INFO     In folder 'mbed-os-example-tls/benchmark'
[EXAMPLES]> INFO     In folder 'mbed-os-example-tls/tls-client'
[EXAMPLES]> INFO     In folder 'mbed-os-example-tls/hashing'
[EXAMPLES]> INFO     In folder 'mbed-os-example-tls/authcrypt'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_Advertising'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GAP'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GattClient_CharacteristicUpdates'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GattClient_CharacteristicWrite'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GattServer_AddService'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GattServer_CharacteristicUpdates'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_GattServer_CharacteristicWrite'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_PeriodicAdvertising'
[EXAMPLES]> INFO     In folder 'mbed-os-example-ble/BLE_SecurityAndPrivacy'
[EXAMPLES]> INFO     In folder 'mbed-os-example-sockets'
[EXAMPLES]> INFO     In folder 'mbed-os-example-cellular'
[EXAMPLES]> INFO     In folder 'mbed-os-example-lorawan'
[EXAMPLES]> INFO     In folder 'mbed-os-example-devicekey'
[EXAMPLES]> INFO     In folder 'mbed-os-example-thread-statistics'
[EXAMPLES]> INFO     In folder 'mbed-os-example-sys-info'
[EXAMPLES]> INFO     In folder 'mbed-os-example-cpu-stats'
[EXAMPLES]> INFO     In folder 'mbed-os-example-socket-stats'
[EXAMPLES]> INFO     In folder 'mbed-os-example-error-handling'
[EXAMPLES]> INFO     In folder 'mbed-os-example-filesystem'
[EXAMPLES]> INFO     In folder 'mbed-os-example-mesh-minimal'
[EXAMPLES]> INFO     Compiling mbed-os-example-mesh-minimal NUCLEO_F767ZI GCC_ARM
[EXAMPLES]> INFO     Executing command 'mbed-tools compile -t GCC_ARM -m NUCLEO_F767ZI -c'...

#### STDOUT ####
Configuring project and generating build system...
-- The C compiler identification is GNU 9.2.1
-- The CXX compiler identification is GNU 9.2.1
-- The ASM compiler identification is GNU
-- Found assembler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/local/gcc-arm-none-eabi-9-2019-q4-major/bin/arm-none-eabi-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Python3: /usr/bin/python3.7 (found version "3.7.4") found components: Interpreter 
-- Checking for Python package prettytable -- found
-- Checking for Python package future -- found
-- Checking for Python package jinja2 -- found
-- Checking for Python package intelhex -- found
-- Configuring incomplete, errors occurred!
See also "/builds/workspace/mbed-os-ci_cmake-example-GCC_ARM-dev@2/examples/mbed-os-example-mesh-minimal/cmake_build/NUCLEO_F767ZI/develop/GCC_ARM/CMakeFiles/CMakeOutput.log".
See also "/builds/workspace/mbed-os-ci_cmake-example-GCC_ARM-dev@2/examples/mbed-os-example-mesh-minimal/cmake_build/NUCLEO_F767ZI/develop/GCC_ARM/CMakeFiles/CMakeError.log".

#### STDERR ####
CMake Error at CMakeLists.txt:18 (mbed_set_mbed_target_linker_script):
  Unknown CMake command "mbed_set_mbed_target_linker_script".

ERROR: CMake invocation failed!

More information may be available by using the command line option '-v'.

#### End of STDOUT/STDERR ####

[EXAMPLES]> INFO     In folder 'mbed-os-example-bootloader'
[EXAMPLES]> INFO     In folder 'mbed-os-example-mbed-crypto/getting-started'
[EXAMPLES]> INFO     In folder 'mbed-os-example-psa'
[EXAMPLES]> INFO     In folder 'mbed-os-example-nfc/NFC_EEPROM'
[EXAMPLES]> INFO     In folder 'mbed-os-example-nfc/NFC_SmartPoster'
[EXAMPLES]> INFO     In folder 'mbed-os-example-blockdevice'
[EXAMPLES]> INFO     In folder 'mbed-os-example-kvstore'
[EXAMPLES]> INFO     In folder 'mbed-os-example-crash-reporting'
[EXAMPLES]> INFO     In folder 'mbed-os-example-sd-driver'
[EXAMPLES]> INFO     In folder 'mbed-os-example-attestation'
[EXAMPLES]> INFO     In folder 'mbed-os-example-atecc608a/atecc608a'

Passed Example Compilation:
+------------------------+---------------+-----------+----------+--------------+
| EXAMPLE NAME           |     TARGET    | TOOLCHAIN | TEST GEN | BUILD RESULT |
+------------------------+---------------+-----------+----------+--------------+
| mbed-os-example-blinky | NUCLEO_F767ZI |  GCC_ARM  | TEST_OFF |    PASSED    |
+------------------------+---------------+-----------+----------+--------------+

Failed Example Compilation:
+------------------------------+---------------+-----------+----------+--------------+
| EXAMPLE NAME                 |     TARGET    | TOOLCHAIN | TEST GEN | BUILD RESULT |
+------------------------------+---------------+-----------+----------+--------------+
| mbed-os-example-mesh-minimal | NUCLEO_F767ZI |  GCC_ARM  |  UNSET   |    FAILED    |
+------------------------------+---------------+-----------+----------+--------------+
Number of failures = 1

#### Target(s) affected by this defect ?

All

#### Toolchain(s) (name and version) displaying this defect ?

GCC_ARM, ARM

#### What version of Mbed-os are you using (tag or sha) ?

mbed-os-0.0.0

#### What version(s) of tools are you using. List all that apply (E.g. mbed-cli)

Mbed CLI 2 7.8.0

#### How is this defect reproduced ?

`mbed-tools compile -t GCC_ARM -m NUCLEO_F767ZI -c`

**Comment by ciarmcom** [comment]
Thank you for raising this detailed GitHub issue. I am now notifying our internal issue triagers. 
*Internal Jira reference: https://jira.arm.com/browse/IOTOSM-3784*

**Comment by Patater** [comment]
https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/332 merged
