### ISSUE TITLE
build error with ncs36510-rf-driver

### ISSUE THREAD

**Issue by maclobdell** [ARMmbed/mbed-os-example-mesh-minimal#7]
The following steps yield the build error below.  This swaps out the core mbed library with the fork for on-semi's development.  Then swaps out the rf driver.

git clone https://github.com/ARMmbed/mbed-os-example-mesh-minimal.git
cd mbed-os-example-mesh-minimal
cd mbed-os
mbed remove core
mbed add https://github.com/ARMmbed/mbed-on-semi core
cd ..
mbed remove atmel-rf-driver
mbed add ncs36510-rf-driver
mbed compile -t GCC_ARM -m NCS36510

Compile: NanostackInterface.cpp
[Error] NanostackInterface.cpp@470: too few arguments to function 'int8_t rf_device_register(const uint8_t*)'
.\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp: In member function 'int MeshInterfaceNanostack::register_rf()':
.\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp:470:39: error: too few arguments to function 'int8_t rf_device_register(const uint8_t*)'
     rf_device_id = rf_device_register();
                                       ^
In file included from .\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp:30:0:
./ncs36510-rf-driver/ncs36510-rf-driver/driverRFPhy.h:18:8: note: declared here
 int8_t rf_device_register(const uint8_t *address_ptr);
        ^
[ERROR] .\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp: In member function 'int MeshInterfaceNanostack::register_rf()':
.\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp:470:39: error: too few arguments to function 'int8_t rf_device_register(const uint8_t*)'
     rf_device_id = rf_device_register();
                                       ^
In file included from .\mbed-os\features\FEATURE_IPV6\nanostack-interface\NanostackInterface.cpp:30:0:
./ncs36510-rf-driver/ncs36510-rf-driver/driverRFPhy.h:18:8: note: declared here
 int8_t rf_device_register(const uint8_t *address_ptr);
        ^

[mbed] ERROR: "python" returned error code 1.
[mbed] ERROR: Command "python -u C:\Users\maclob01\Documents\morpheus\onsemi\mbed-os-example-mesh-minimal\mbed-os\core\tools\make.py -t GCC_ARM -m NCS36510 --source . --build .\.build\NCS36510\GCC_ARM
" in "C:\Users\maclob01\Documents\morpheus\onsemi\mbed-os-example-mesh-minimal"

**Comment by SeppoTakalo** [comment]
Please be advised,
this issue will be fixed once we merge in the https://github.com/ARMmbed/mbed-os-example-mesh-minimal/pull/25

ncs36510 driver is already in mbed-OS master so once the release or RC is out, we can merge that PR in.

**Comment by SeppoTakalo** [comment]
Issue is now fixed with mbed OS 5.2 release.
