### ISSUE TITLE
[OoB_5_5] Compiler warnings

### ISSUE THREAD

**Issue by AriParkkila** [ARMmbed/mbed-os-example-mesh-minimal#90]
Compiler warnings should be removed, see logs below.

ARM 5.06u5 log: mbed compile -t ARM -m NUCLEO_F411RE
[log.txt](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/files/1068213/log.txt)

GCC 6.3.1 log: mbed compile -t GCC_ARM -m NUCLEO_F411RE
[log.txt](https://github.com/ARMmbed/mbed-os-example-mesh-minimal/files/1068222/log.txt)

**Comment by 0xc0170** [comment]
@AriParkkila Please provide more details. The headline should show what is the issue, build error for this target, or similar. The body of the issue details to reproduce. The logs are nice to have, but would be better if the bug report would contain at least one paragraph with description how to reproduce and what are the symptoms (if runtime error, then how it fails, call stack, code snippet, anything that helps).

**Comment by AriParkkila** [comment]
Thanks for response. All compiler warnings should be removed due to each warning is a potential program defect, fails to build with -Wall flags and also excessive (even false positive) warnings may hide any real problems.

The logs contain compiler configuration, as an example NUCLEO_F411RE, ARM:
mbed compile -t GCC_ARM -m NUCLEO_F411RE

I updated the compile commands to issue description.

**Comment by SeppoTakalo** [comment]
I agree, there should not be any compiler warnings when building a released code.
We keep this open until warnings are fixed.

**Comment by SeppoTakalo** [comment]
Fixed in https://github.com/ARMmbed/mbed-os/pull/4738
