### ISSUE TITLE
Throwing errors when running uVision's and make_arm5c's compiled version of program.

### ISSUE THREAD

**Issue by brandonboesch** [ARMmbed/mbed-os-example-mesh-minimal#94]
When running after exporting and compiling in uVision, the following error occurs on serial output:

Mutex 20000490 error -6: Not allowed in ISR context

**Comment by SeppoTakalo** [comment]
Can you tell me what target board this is, and output of `mbed ls`

**Comment by SeppoTakalo** [comment]
Also, can you provide me a call stack from the error condition.
Thanks.

**Comment by brandonboesch** [comment]
I am using a KW24D. The output of `mbed ls` is:
![image](https://user-images.githubusercontent.com/16062082/27144346-0cbdbf36-50f7-11e7-82b1-1e2a62852e02.png)

The call stack the moment before the error is thrown is here:
![capture](https://user-images.githubusercontent.com/16062082/27144363-25c1309e-50f7-11e7-81f8-e39875861a8a.PNG)

**Comment by brandonboesch** [comment]
I just tried using running the program after exporting and compiling for make_arm5c, and received the same error:
Mutex 1fff8c98 error -6: Not allowed in ISR context

**Comment by SeppoTakalo** [comment]
Thanks.
This looks clear now. MCR20A driver is calling Nanostack's API from IRQ context.
We should report this issue there.

**Comment by ashok-rao** [comment]
@0xc0170 .. looks like this one is for MCR20 driver authors. Can you please tag relevant people? Thanks.

**Comment by 0xc0170** [comment]
> @0xc0170 .. looks like this one is for MCR20 driver authors. Can you please tag relevant people? Thanks.

@SeppoTakalo should know better, can you please?

**Comment by MarceloSalazar** [comment]
@SeppoTakalo please comment

**Comment by ciarmcom** [comment]
ARM Internal Ref: ONME-3193

**Comment by SeppoTakalo** [comment]
This was fixed in https://github.com/ARMmbed/mcr20a-rf-driver/commit/72f895683b49bce928fbfaddd7d64ab681122eec

Needs re-testing in Uvision

**Comment by mray19027** [comment]
Confirmed this works in Uvision5 using exporters
